services:

  servidor:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DAM
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - servidor
  
  app:
    build: .
    container_name: node_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql-servidor: